# Generated by Django 4.1 on 2022-10-02 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.CharField(max_length=90, verbose_name='Correo Electrónico')),
                ('tipo_servicio', models.CharField(max_length=150, verbose_name='Tipo de Servicio')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Cargo', models.CharField(max_length=40, verbose_name='Cargo')),
                ('Tipo_Contrato', models.CharField(max_length=40, verbose_name='Tipo Contrato')),
                ('hora', models.DurationField(verbose_name='Hora de ingreso')),
                ('hora2', models.DurationField(verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha de salida')),
                ('empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleados')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Utilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Cantidad')),
                ('disponible', models.BooleanField(verbose_name='¿Producto Disponible?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario')),
            ],
            options={
                'verbose_name': 'Utilidad',
                'verbose_name_plural': 'Utilidades',
                'db_table': 'Utilidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50, verbose_name='Nombre Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha Final')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('empleados', models.ManyToManyField(to='core.empleados')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'Proyecto',
                'ordering': ['id'],
            },
        ),
    ]
